version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: Gokul@123
      MYSQL_DATABASE: student_details
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    container_name: my-cicd-demo
    depends_on:
      - mysql
    ports:
      - "6060:6060"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/student_details
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Gokul@123
    restart: always

volumes:
  mysql-data: